wallpaper {
    monitor = HDMI-A-2
    path = ~/walls/dual_first_half.jpg
    fit_mode = cover
}

wallpaper {
    monitor = DP-2
    path = ~/walls/dual_second_half.jpg
    fit_mode = cover
}

wallpaper {
    monitor = 
    path = ~/walls/dual.jpg
    fit_mode = cover
}

# ...
