wallpaper {
    monitor = DP-3
    path = ~/walls/arch_btw_rosepine.png
    fit_mode = cover
}

wallpaper {
    monitor = DP-2
    path = ~/walls/arch_btw_rosepine.png
    fit_mode = cover
}

wallpaper {
    monitor = 
    path = ~/walls/arch_btw_rosepine.png
    fit_mode = cover
}

# ...
