wallpaper {
    monitor = DP-3
    path = ~/walls/nord_sky.png
    fit_mode = cover
}

wallpaper {
    monitor = DP-2
    path = ~/walls/nord_sky.png
    fit_mode = cover
}

wallpaper {
    monitor = 
    path = ~/walls/nord_sky.png
    fit_mode = cover
}

# ...
