-- hyprland.lua
-- Generated by hypr-migrate from: rose-pine.conf
-- Hyprland >= 0.55 required — https://wiki.hypr.land/
--
-- MIGRATION SUMMARY:
--   Variables:       15 resolved
--   Config keys:     0 emitted
--   Monitors:        0
--   Keybinds:        0 total, 0 collapsed into loops
--   Window rules:    0 total, 0 merged
--   Workspace rules: 0
--   Exec commands:   0
--   Gestures:        0
--   Warnings:        0  ← search MIGRATION_WARNING
--   Review needed:   0  ← search MIGRATION_NOTE
--
-- IMPORTANT: Verify output against https://wiki.hypr.land/ before use
-- The wiki is the only authoritative reference for Lua syntax.

return {
	base = "rgba(191724ff)",
	surface = "rgba(1f1d2eff)",
	overlay = "rgba(26233aff)",
	muted = "rgba(6e6a86ff)",
	subtle = "rgba(908caaff)",
	text = "rgba(e0def4ff)",
	love = "rgba(eb6f92ff)",
	gold = "rgba(f6c177ff)",
	rose = "rgba(ebbcbaff)",
	pine = "rgba(31748fff)",
	foam = "rgba(9ccfd8ff)",
	iris = "rgba(c4a7e7ff)",
	highlightLow = "rgba(21202eff)",
	highlightMed = "rgba(403d52ff)",
	highlightHigh = "rgba(524f67ff)",
}
